# Generated by Django 5.1.4 on 2026-08-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_date_effective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costitem',
            name='description',
        ),
    ]
