# Generated by Django 5.1.4 on 2026-08-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_remove_costitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='costitem',
            name='unit',
            field=models.CharField(choices=[('pcs', 'pcs'), ('kg', 'kg'), ('g', 'g'), ('L', 'L'), ('mL', 'mL')], default='pcs', max_length=8),
        ),
    ]
