# Generated by Django 5.1.4 on 2026-09-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_costitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='costlist',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/'),
        ),
    ]
